name: taste_protos
description: Taste Protos

environment:
  sdk: ">=2.8.0-dev.12.0.flutter-9983424a3c <3.0.0"

dependencies:
  protoc_plugin:
  equatable:
  edit_distance:
  protobuf:
  freezed_annotation:
  tuple:

dev_dependencies:
  build_runner:
  pedantic:
  test:
  freezed:

dependency_overrides:
  protoc_plugin:
    git:
      url: https://github.com/dart-lang/protobuf
      path: protoc_plugin
      ref: master
  protobuf:
    git:
      url: https://github.com/dart-lang/protobuf
      path: protobuf
      ref: master
