# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud_functions.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cloud_functions.proto',
  package='cloud_functions',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x63loud_functions.proto\x12\x0f\x63loud_functions\"I\n\x18GenerateAuthTokenRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x1b\n\x19GenerateAuthTokenResponse\"T\n\x14ResolveReportRequest\x12\x0e\n\x06report\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x1e\n\x16send_user_notification\x18\x03 \x01(\x08\"\x17\n\x15ResolveReportResponse\"&\n\x16GetIsFoodStatusRequest\x12\x0c\n\x04urls\x18\x01 \x03(\t\"0\n\x17GetIsFoodStatusResponse\x12\x15\n\rfraction_food\x18\x01 \x01(\x01\"1\n\x1dQueueInstagramUsernameRequest\x12\x10\n\x08username\x18\x01 \x01(\t\" \n\x1eQueueInstagramUsernameResponseb\x06proto3'
)




_GENERATEAUTHTOKENREQUEST = _descriptor.Descriptor(
  name='GenerateAuthTokenRequest',
  full_name='cloud_functions.GenerateAuthTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='cloud_functions.GenerateAuthTokenRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='full_name', full_name='cloud_functions.GenerateAuthTokenRequest.full_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='cloud_functions.GenerateAuthTokenRequest.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=115,
)


_GENERATEAUTHTOKENRESPONSE = _descriptor.Descriptor(
  name='GenerateAuthTokenResponse',
  full_name='cloud_functions.GenerateAuthTokenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=144,
)


_RESOLVEREPORTREQUEST = _descriptor.Descriptor(
  name='ResolveReportRequest',
  full_name='cloud_functions.ResolveReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='report', full_name='cloud_functions.ResolveReportRequest.report', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='cloud_functions.ResolveReportRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='send_user_notification', full_name='cloud_functions.ResolveReportRequest.send_user_notification', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=230,
)


_RESOLVEREPORTRESPONSE = _descriptor.Descriptor(
  name='ResolveReportResponse',
  full_name='cloud_functions.ResolveReportResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=255,
)


_GETISFOODSTATUSREQUEST = _descriptor.Descriptor(
  name='GetIsFoodStatusRequest',
  full_name='cloud_functions.GetIsFoodStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='urls', full_name='cloud_functions.GetIsFoodStatusRequest.urls', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=295,
)


_GETISFOODSTATUSRESPONSE = _descriptor.Descriptor(
  name='GetIsFoodStatusResponse',
  full_name='cloud_functions.GetIsFoodStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fraction_food', full_name='cloud_functions.GetIsFoodStatusResponse.fraction_food', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=345,
)


_QUEUEINSTAGRAMUSERNAMEREQUEST = _descriptor.Descriptor(
  name='QueueInstagramUsernameRequest',
  full_name='cloud_functions.QueueInstagramUsernameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='cloud_functions.QueueInstagramUsernameRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=396,
)


_QUEUEINSTAGRAMUSERNAMERESPONSE = _descriptor.Descriptor(
  name='QueueInstagramUsernameResponse',
  full_name='cloud_functions.QueueInstagramUsernameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=430,
)

DESCRIPTOR.message_types_by_name['GenerateAuthTokenRequest'] = _GENERATEAUTHTOKENREQUEST
DESCRIPTOR.message_types_by_name['GenerateAuthTokenResponse'] = _GENERATEAUTHTOKENRESPONSE
DESCRIPTOR.message_types_by_name['ResolveReportRequest'] = _RESOLVEREPORTREQUEST
DESCRIPTOR.message_types_by_name['ResolveReportResponse'] = _RESOLVEREPORTRESPONSE
DESCRIPTOR.message_types_by_name['GetIsFoodStatusRequest'] = _GETISFOODSTATUSREQUEST
DESCRIPTOR.message_types_by_name['GetIsFoodStatusResponse'] = _GETISFOODSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['QueueInstagramUsernameRequest'] = _QUEUEINSTAGRAMUSERNAMEREQUEST
DESCRIPTOR.message_types_by_name['QueueInstagramUsernameResponse'] = _QUEUEINSTAGRAMUSERNAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenerateAuthTokenRequest = _reflection.GeneratedProtocolMessageType('GenerateAuthTokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEAUTHTOKENREQUEST,
  '__module__' : 'cloud_functions_pb2'
  # @@protoc_insertion_point(class_scope:cloud_functions.GenerateAuthTokenRequest)
  })
_sym_db.RegisterMessage(GenerateAuthTokenRequest)

GenerateAuthTokenResponse = _reflection.GeneratedProtocolMessageType('GenerateAuthTokenResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEAUTHTOKENRESPONSE,
  '__module__' : 'cloud_functions_pb2'
  # @@protoc_insertion_point(class_scope:cloud_functions.GenerateAuthTokenResponse)
  })
_sym_db.RegisterMessage(GenerateAuthTokenResponse)

ResolveReportRequest = _reflection.GeneratedProtocolMessageType('ResolveReportRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESOLVEREPORTREQUEST,
  '__module__' : 'cloud_functions_pb2'
  # @@protoc_insertion_point(class_scope:cloud_functions.ResolveReportRequest)
  })
_sym_db.RegisterMessage(ResolveReportRequest)

ResolveReportResponse = _reflection.GeneratedProtocolMessageType('ResolveReportResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESOLVEREPORTRESPONSE,
  '__module__' : 'cloud_functions_pb2'
  # @@protoc_insertion_point(class_scope:cloud_functions.ResolveReportResponse)
  })
_sym_db.RegisterMessage(ResolveReportResponse)

GetIsFoodStatusRequest = _reflection.GeneratedProtocolMessageType('GetIsFoodStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETISFOODSTATUSREQUEST,
  '__module__' : 'cloud_functions_pb2'
  # @@protoc_insertion_point(class_scope:cloud_functions.GetIsFoodStatusRequest)
  })
_sym_db.RegisterMessage(GetIsFoodStatusRequest)

GetIsFoodStatusResponse = _reflection.GeneratedProtocolMessageType('GetIsFoodStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETISFOODSTATUSRESPONSE,
  '__module__' : 'cloud_functions_pb2'
  # @@protoc_insertion_point(class_scope:cloud_functions.GetIsFoodStatusResponse)
  })
_sym_db.RegisterMessage(GetIsFoodStatusResponse)

QueueInstagramUsernameRequest = _reflection.GeneratedProtocolMessageType('QueueInstagramUsernameRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUEUEINSTAGRAMUSERNAMEREQUEST,
  '__module__' : 'cloud_functions_pb2'
  # @@protoc_insertion_point(class_scope:cloud_functions.QueueInstagramUsernameRequest)
  })
_sym_db.RegisterMessage(QueueInstagramUsernameRequest)

QueueInstagramUsernameResponse = _reflection.GeneratedProtocolMessageType('QueueInstagramUsernameResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUEUEINSTAGRAMUSERNAMERESPONSE,
  '__module__' : 'cloud_functions_pb2'
  # @@protoc_insertion_point(class_scope:cloud_functions.QueueInstagramUsernameResponse)
  })
_sym_db.RegisterMessage(QueueInstagramUsernameResponse)


# @@protoc_insertion_point(module_scope)
