# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import firebase_rules_options_pb2 as firebase__rules__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='common',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1c\x66irebase_rules_options.proto\"p\n\x06\x45xtras\x12.\n\ncreated_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp:\x06\xea\x94-\x02 \x01\"&\n\x16\x44ocumentReferenceProto\x12\x0c\n\x04path\x18\x01 \x01(\t\"-\n\x06LatLng\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"B\n\x0f\x46irebaseStorage\x12\x0c\n\x04\x66ull\x18\x01 \x01(\t\x12\x0e\n\x06medium\x18\x02 \x01(\t\x12\x11\n\tthumbnail\x18\x03 \x01(\t\"x\n\x0b\x41ppMetadata\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12\x10\n\x08\x61pp_name\x18\x02 \x01(\t\x12\x18\n\x10platform_version\x18\x03 \x01(\t\x12\x14\n\x0cproject_code\x18\x04 \x01(\t\x12\x17\n\x0fproject_version\x18\x05 \x01(\t\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"*\n\x07Polygon\x12\x1f\n\x08vertices\x18\x01 \x03(\x0b\x32\r.common.Point\"%\n\x04Size\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"C\n\x18\x44uplicateFbPlaceIdRecord\x12\x14\n\x0c\x64uplicate_id\x18\x01 \x01(\x12\x12\x11\n\tsource_id\x18\x02 \x01(\x12\"H\n\x13\x46\x62PlaceIdDuplicates\x12\x31\n\x07records\x18\x01 \x03(\x0b\x32 .common.DuplicateFbPlaceIdRecordb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,firebase__rules__options__pb2.DESCRIPTOR,])




_EXTRAS = _descriptor.Descriptor(
  name='Extras',
  full_name='common.Extras',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='created_at', full_name='common.Extras.created_at', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updated_at', full_name='common.Extras.updated_at', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\352\224-\002 \001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=199,
)


_DOCUMENTREFERENCEPROTO = _descriptor.Descriptor(
  name='DocumentReferenceProto',
  full_name='common.DocumentReferenceProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='common.DocumentReferenceProto.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=239,
)


_LATLNG = _descriptor.Descriptor(
  name='LatLng',
  full_name='common.LatLng',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='common.LatLng.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='common.LatLng.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=286,
)


_FIREBASESTORAGE = _descriptor.Descriptor(
  name='FirebaseStorage',
  full_name='common.FirebaseStorage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='full', full_name='common.FirebaseStorage.full', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='medium', full_name='common.FirebaseStorage.medium', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thumbnail', full_name='common.FirebaseStorage.thumbnail', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=354,
)


_APPMETADATA = _descriptor.Descriptor(
  name='AppMetadata',
  full_name='common.AppMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_id', full_name='common.AppMetadata.app_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='app_name', full_name='common.AppMetadata.app_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='platform_version', full_name='common.AppMetadata.platform_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_code', full_name='common.AppMetadata.project_code', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_version', full_name='common.AppMetadata.project_version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=476,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='common.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='common.Point.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='common.Point.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=478,
  serialized_end=507,
)


_POLYGON = _descriptor.Descriptor(
  name='Polygon',
  full_name='common.Polygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vertices', full_name='common.Polygon.vertices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=509,
  serialized_end=551,
)


_SIZE = _descriptor.Descriptor(
  name='Size',
  full_name='common.Size',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='common.Size.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='common.Size.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=590,
)


_DUPLICATEFBPLACEIDRECORD = _descriptor.Descriptor(
  name='DuplicateFbPlaceIdRecord',
  full_name='common.DuplicateFbPlaceIdRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='duplicate_id', full_name='common.DuplicateFbPlaceIdRecord.duplicate_id', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_id', full_name='common.DuplicateFbPlaceIdRecord.source_id', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=592,
  serialized_end=659,
)


_FBPLACEIDDUPLICATES = _descriptor.Descriptor(
  name='FbPlaceIdDuplicates',
  full_name='common.FbPlaceIdDuplicates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='common.FbPlaceIdDuplicates.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=661,
  serialized_end=733,
)

_EXTRAS.fields_by_name['created_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_EXTRAS.fields_by_name['updated_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_POLYGON.fields_by_name['vertices'].message_type = _POINT
_FBPLACEIDDUPLICATES.fields_by_name['records'].message_type = _DUPLICATEFBPLACEIDRECORD
DESCRIPTOR.message_types_by_name['Extras'] = _EXTRAS
DESCRIPTOR.message_types_by_name['DocumentReferenceProto'] = _DOCUMENTREFERENCEPROTO
DESCRIPTOR.message_types_by_name['LatLng'] = _LATLNG
DESCRIPTOR.message_types_by_name['FirebaseStorage'] = _FIREBASESTORAGE
DESCRIPTOR.message_types_by_name['AppMetadata'] = _APPMETADATA
DESCRIPTOR.message_types_by_name['Point'] = _POINT
DESCRIPTOR.message_types_by_name['Polygon'] = _POLYGON
DESCRIPTOR.message_types_by_name['Size'] = _SIZE
DESCRIPTOR.message_types_by_name['DuplicateFbPlaceIdRecord'] = _DUPLICATEFBPLACEIDRECORD
DESCRIPTOR.message_types_by_name['FbPlaceIdDuplicates'] = _FBPLACEIDDUPLICATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Extras = _reflection.GeneratedProtocolMessageType('Extras', (_message.Message,), {
  'DESCRIPTOR' : _EXTRAS,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.Extras)
  })
_sym_db.RegisterMessage(Extras)

DocumentReferenceProto = _reflection.GeneratedProtocolMessageType('DocumentReferenceProto', (_message.Message,), {
  'DESCRIPTOR' : _DOCUMENTREFERENCEPROTO,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.DocumentReferenceProto)
  })
_sym_db.RegisterMessage(DocumentReferenceProto)

LatLng = _reflection.GeneratedProtocolMessageType('LatLng', (_message.Message,), {
  'DESCRIPTOR' : _LATLNG,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.LatLng)
  })
_sym_db.RegisterMessage(LatLng)

FirebaseStorage = _reflection.GeneratedProtocolMessageType('FirebaseStorage', (_message.Message,), {
  'DESCRIPTOR' : _FIREBASESTORAGE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.FirebaseStorage)
  })
_sym_db.RegisterMessage(FirebaseStorage)

AppMetadata = _reflection.GeneratedProtocolMessageType('AppMetadata', (_message.Message,), {
  'DESCRIPTOR' : _APPMETADATA,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.AppMetadata)
  })
_sym_db.RegisterMessage(AppMetadata)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.Point)
  })
_sym_db.RegisterMessage(Point)

Polygon = _reflection.GeneratedProtocolMessageType('Polygon', (_message.Message,), {
  'DESCRIPTOR' : _POLYGON,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.Polygon)
  })
_sym_db.RegisterMessage(Polygon)

Size = _reflection.GeneratedProtocolMessageType('Size', (_message.Message,), {
  'DESCRIPTOR' : _SIZE,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.Size)
  })
_sym_db.RegisterMessage(Size)

DuplicateFbPlaceIdRecord = _reflection.GeneratedProtocolMessageType('DuplicateFbPlaceIdRecord', (_message.Message,), {
  'DESCRIPTOR' : _DUPLICATEFBPLACEIDRECORD,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.DuplicateFbPlaceIdRecord)
  })
_sym_db.RegisterMessage(DuplicateFbPlaceIdRecord)

FbPlaceIdDuplicates = _reflection.GeneratedProtocolMessageType('FbPlaceIdDuplicates', (_message.Message,), {
  'DESCRIPTOR' : _FBPLACEIDDUPLICATES,
  '__module__' : 'common_pb2'
  # @@protoc_insertion_point(class_scope:common.FbPlaceIdDuplicates)
  })
_sym_db.RegisterMessage(FbPlaceIdDuplicates)


_EXTRAS._options = None
# @@protoc_insertion_point(module_scope)
