# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: firebase_rules_options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='firebase_rules_options.proto',
  package='rules_gen',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x66irebase_rules_options.proto\x12\trules_gen\x1a google/protobuf/descriptor.proto\"z\n\x13RulesMessageOptions\x12\x10\n\x08validate\x18\x01 \x01(\t\x12\x1f\n\x10\x65xtra_properties\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x08nullable\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x08required\x18\x04 \x01(\x08:\x05\x66\x61lse\"\xc2\x01\n\x11RulesFieldOptions\x12\x10\n\x08validate\x18\x01 \x01(\t\x12\x1d\n\x0ereference_type\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x08nullable\x18\x03 \x01(\x08:\x05\x66\x61lse\x12\x18\n\tauth_user\x18\x04 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x08required\x18\x05 \x01(\x08:\x05\x66\x61lse\x12\x18\n\tnot_empty\x18\x06 \x01(\x08:\x05\x66\x61lse\x12\x16\n\x07is_http\x18\x07 \x01(\x08:\x05\x66\x61lse\"5\n\x10RulesFileOptions\x12!\n\x12\x66ull_package_names\x18\x01 \x01(\x08:\x05\x66\x61lse\"/\n\x10RulesEnumOptions\x12\x1b\n\rstring_values\x18\x01 \x01(\x08:\x04true:R\n\x07message\x12\x1f.google.protobuf.MessageOptions\x18\xcd\xd2\x05 \x01(\x0b\x32\x1e.rules_gen.RulesMessageOptions:L\n\x05\x66ield\x12\x1d.google.protobuf.FieldOptions\x18\xcd\xd2\x05 \x01(\x0b\x32\x1c.rules_gen.RulesFieldOptions:S\n\x0e\x66irebase_rules\x12\x1c.google.protobuf.FileOptions\x18\xcd\xd2\x05 \x01(\x0b\x32\x1b.rules_gen.RulesFileOptions:X\n\x13\x66irebase_rules_enum\x12\x1c.google.protobuf.EnumOptions\x18\xcd\xd2\x05 \x01(\x0b\x32\x1b.rules_gen.RulesEnumOptions'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


MESSAGE_FIELD_NUMBER = 92493
message = _descriptor.FieldDescriptor(
  name='message', full_name='rules_gen.message', index=0,
  number=92493, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
FIELD_FIELD_NUMBER = 92493
field = _descriptor.FieldDescriptor(
  name='field', full_name='rules_gen.field', index=1,
  number=92493, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
FIREBASE_RULES_FIELD_NUMBER = 92493
firebase_rules = _descriptor.FieldDescriptor(
  name='firebase_rules', full_name='rules_gen.firebase_rules', index=2,
  number=92493, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
FIREBASE_RULES_ENUM_FIELD_NUMBER = 92493
firebase_rules_enum = _descriptor.FieldDescriptor(
  name='firebase_rules_enum', full_name='rules_gen.firebase_rules_enum', index=3,
  number=92493, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)


_RULESMESSAGEOPTIONS = _descriptor.Descriptor(
  name='RulesMessageOptions',
  full_name='rules_gen.RulesMessageOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='validate', full_name='rules_gen.RulesMessageOptions.validate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra_properties', full_name='rules_gen.RulesMessageOptions.extra_properties', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nullable', full_name='rules_gen.RulesMessageOptions.nullable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='required', full_name='rules_gen.RulesMessageOptions.required', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=199,
)


_RULESFIELDOPTIONS = _descriptor.Descriptor(
  name='RulesFieldOptions',
  full_name='rules_gen.RulesFieldOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='validate', full_name='rules_gen.RulesFieldOptions.validate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reference_type', full_name='rules_gen.RulesFieldOptions.reference_type', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nullable', full_name='rules_gen.RulesFieldOptions.nullable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='auth_user', full_name='rules_gen.RulesFieldOptions.auth_user', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='required', full_name='rules_gen.RulesFieldOptions.required', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='not_empty', full_name='rules_gen.RulesFieldOptions.not_empty', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_http', full_name='rules_gen.RulesFieldOptions.is_http', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=396,
)


_RULESFILEOPTIONS = _descriptor.Descriptor(
  name='RulesFileOptions',
  full_name='rules_gen.RulesFileOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='full_package_names', full_name='rules_gen.RulesFileOptions.full_package_names', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=398,
  serialized_end=451,
)


_RULESENUMOPTIONS = _descriptor.Descriptor(
  name='RulesEnumOptions',
  full_name='rules_gen.RulesEnumOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_values', full_name='rules_gen.RulesEnumOptions.string_values', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=500,
)

DESCRIPTOR.message_types_by_name['RulesMessageOptions'] = _RULESMESSAGEOPTIONS
DESCRIPTOR.message_types_by_name['RulesFieldOptions'] = _RULESFIELDOPTIONS
DESCRIPTOR.message_types_by_name['RulesFileOptions'] = _RULESFILEOPTIONS
DESCRIPTOR.message_types_by_name['RulesEnumOptions'] = _RULESENUMOPTIONS
DESCRIPTOR.extensions_by_name['message'] = message
DESCRIPTOR.extensions_by_name['field'] = field
DESCRIPTOR.extensions_by_name['firebase_rules'] = firebase_rules
DESCRIPTOR.extensions_by_name['firebase_rules_enum'] = firebase_rules_enum
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RulesMessageOptions = _reflection.GeneratedProtocolMessageType('RulesMessageOptions', (_message.Message,), {
  'DESCRIPTOR' : _RULESMESSAGEOPTIONS,
  '__module__' : 'firebase_rules_options_pb2'
  # @@protoc_insertion_point(class_scope:rules_gen.RulesMessageOptions)
  })
_sym_db.RegisterMessage(RulesMessageOptions)

RulesFieldOptions = _reflection.GeneratedProtocolMessageType('RulesFieldOptions', (_message.Message,), {
  'DESCRIPTOR' : _RULESFIELDOPTIONS,
  '__module__' : 'firebase_rules_options_pb2'
  # @@protoc_insertion_point(class_scope:rules_gen.RulesFieldOptions)
  })
_sym_db.RegisterMessage(RulesFieldOptions)

RulesFileOptions = _reflection.GeneratedProtocolMessageType('RulesFileOptions', (_message.Message,), {
  'DESCRIPTOR' : _RULESFILEOPTIONS,
  '__module__' : 'firebase_rules_options_pb2'
  # @@protoc_insertion_point(class_scope:rules_gen.RulesFileOptions)
  })
_sym_db.RegisterMessage(RulesFileOptions)

RulesEnumOptions = _reflection.GeneratedProtocolMessageType('RulesEnumOptions', (_message.Message,), {
  'DESCRIPTOR' : _RULESENUMOPTIONS,
  '__module__' : 'firebase_rules_options_pb2'
  # @@protoc_insertion_point(class_scope:rules_gen.RulesEnumOptions)
  })
_sym_db.RegisterMessage(RulesEnumOptions)

message.message_type = _RULESMESSAGEOPTIONS
google_dot_protobuf_dot_descriptor__pb2.MessageOptions.RegisterExtension(message)
field.message_type = _RULESFIELDOPTIONS
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(field)
firebase_rules.message_type = _RULESFILEOPTIONS
google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(firebase_rules)
firebase_rules_enum.message_type = _RULESENUMOPTIONS
google_dot_protobuf_dot_descriptor__pb2.EnumOptions.RegisterExtension(firebase_rules_enum)

# @@protoc_insertion_point(module_scope)
