# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import firestore_pb2 as firestore__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='notifications.proto',
  package='notifications',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13notifications.proto\x12\rnotifications\x1a\x0f\x66irestore.proto\"\x83\x01\n\tFcmExtras\x12\x36\n\x11notification_type\x18\x01 \x01(\x0e\x32\x1b.firestore.NotificationType\x12\x19\n\x11notification_path\x18\x02 \x01(\t\x12\x15\n\rdocument_link\x18\x03 \x01(\t\x12\x0c\n\x04user\x18\x04 \x01(\t\"\xef\x01\n\nFcmMessage\x12<\n\x0cnotification\x18\x01 \x01(\x0b\x32&.notifications.FcmMessage.Notification\x12,\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1e.notifications.FcmMessage.Data\x1a+\n\x0cNotification\x12\x0c\n\x04\x62ody\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x1aH\n\x04\x44\x61ta\x12\x0e\n\x06\x65xtras\x18\x01 \x01(\t\x12\x30\n\x0c\x63lick_action\x18\x02 \x01(\x0e\x32\x1a.notifications.ClickAction*-\n\x0b\x43lickAction\x12\x1e\n\x1a\x46LUTTER_NOTIFICATION_CLICK\x10\x00\x62\x06proto3'
  ,
  dependencies=[firestore__pb2.DESCRIPTOR,])

_CLICKACTION = _descriptor.EnumDescriptor(
  name='ClickAction',
  full_name='notifications.ClickAction',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLUTTER_NOTIFICATION_CLICK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=431,
  serialized_end=476,
)
_sym_db.RegisterEnumDescriptor(_CLICKACTION)

ClickAction = enum_type_wrapper.EnumTypeWrapper(_CLICKACTION)
FLUTTER_NOTIFICATION_CLICK = 0



_FCMEXTRAS = _descriptor.Descriptor(
  name='FcmExtras',
  full_name='notifications.FcmExtras',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='notification_type', full_name='notifications.FcmExtras.notification_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='notification_path', full_name='notifications.FcmExtras.notification_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='document_link', full_name='notifications.FcmExtras.document_link', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user', full_name='notifications.FcmExtras.user', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=187,
)


_FCMMESSAGE_NOTIFICATION = _descriptor.Descriptor(
  name='Notification',
  full_name='notifications.FcmMessage.Notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='notifications.FcmMessage.Notification.body', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='notifications.FcmMessage.Notification.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=355,
)

_FCMMESSAGE_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='notifications.FcmMessage.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='extras', full_name='notifications.FcmMessage.Data.extras', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='click_action', full_name='notifications.FcmMessage.Data.click_action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=429,
)

_FCMMESSAGE = _descriptor.Descriptor(
  name='FcmMessage',
  full_name='notifications.FcmMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='notification', full_name='notifications.FcmMessage.notification', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='notifications.FcmMessage.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FCMMESSAGE_NOTIFICATION, _FCMMESSAGE_DATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=429,
)

_FCMEXTRAS.fields_by_name['notification_type'].enum_type = firestore__pb2._NOTIFICATIONTYPE
_FCMMESSAGE_NOTIFICATION.containing_type = _FCMMESSAGE
_FCMMESSAGE_DATA.fields_by_name['click_action'].enum_type = _CLICKACTION
_FCMMESSAGE_DATA.containing_type = _FCMMESSAGE
_FCMMESSAGE.fields_by_name['notification'].message_type = _FCMMESSAGE_NOTIFICATION
_FCMMESSAGE.fields_by_name['data'].message_type = _FCMMESSAGE_DATA
DESCRIPTOR.message_types_by_name['FcmExtras'] = _FCMEXTRAS
DESCRIPTOR.message_types_by_name['FcmMessage'] = _FCMMESSAGE
DESCRIPTOR.enum_types_by_name['ClickAction'] = _CLICKACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FcmExtras = _reflection.GeneratedProtocolMessageType('FcmExtras', (_message.Message,), {
  'DESCRIPTOR' : _FCMEXTRAS,
  '__module__' : 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:notifications.FcmExtras)
  })
_sym_db.RegisterMessage(FcmExtras)

FcmMessage = _reflection.GeneratedProtocolMessageType('FcmMessage', (_message.Message,), {

  'Notification' : _reflection.GeneratedProtocolMessageType('Notification', (_message.Message,), {
    'DESCRIPTOR' : _FCMMESSAGE_NOTIFICATION,
    '__module__' : 'notifications_pb2'
    # @@protoc_insertion_point(class_scope:notifications.FcmMessage.Notification)
    })
  ,

  'Data' : _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
    'DESCRIPTOR' : _FCMMESSAGE_DATA,
    '__module__' : 'notifications_pb2'
    # @@protoc_insertion_point(class_scope:notifications.FcmMessage.Data)
    })
  ,
  'DESCRIPTOR' : _FCMMESSAGE,
  '__module__' : 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:notifications.FcmMessage)
  })
_sym_db.RegisterMessage(FcmMessage)
_sym_db.RegisterMessage(FcmMessage.Notification)
_sym_db.RegisterMessage(FcmMessage.Data)


# @@protoc_insertion_point(module_scope)
