# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='query.proto',
  package='firestore_query',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bquery.proto\x12\x0f\x66irestore_query\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"\xfa\x04\n\x0e\x46irestoreQuery\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x1b\n\x13is_collection_group\x18\x02 \x01(\x08\x12\x42\n\rwhere_clauses\x18\x03 \x03(\x0b\x32+.firestore_query.FirestoreQuery.WhereClause\x12\r\n\x05limit\x18\x04 \x01(\x05\x12\x42\n\rorder_clauses\x18\x05 \x03(\x0b\x32+.firestore_query.FirestoreQuery.OrderClause\x1a\xed\x02\n\x0bWhereClause\x12\x13\n\x0bwhere_field\x18\x01 \x01(\t\x12J\n\ncomparator\x18\x02 \x01(\x0e\x32\x36.firestore_query.FirestoreQuery.WhereClause.Comparator\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12\x39\n\x0freference_value\x18\x04 \x01(\x0b\x32\x1e.common.DocumentReferenceProtoH\x00\x12\x35\n\x0ftimestamp_value\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x12\x13\n\tint_value\x18\x06 \x01(\x05H\x00\x12\x16\n\x0c\x64ouble_value\x18\x07 \x01(\x01H\x00\"7\n\nComparator\x12\x18\n\x14\x43OMPARATOR_UNDEFINED\x10\x00\x12\x0f\n\x0bis_equal_to\x10\x01\x42\r\n\x0bwhere_value\x1a\x36\n\x0bOrderClause\x12\x13\n\x0border_field\x18\x01 \x01(\t\x12\x12\n\ndescending\x18\x02 \x01(\x08\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])



_FIRESTOREQUERY_WHERECLAUSE_COMPARATOR = _descriptor.EnumDescriptor(
  name='Comparator',
  full_name='firestore_query.FirestoreQuery.WhereClause.Comparator',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMPARATOR_UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='is_equal_to', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=588,
  serialized_end=643,
)
_sym_db.RegisterEnumDescriptor(_FIRESTOREQUERY_WHERECLAUSE_COMPARATOR)


_FIRESTOREQUERY_WHERECLAUSE = _descriptor.Descriptor(
  name='WhereClause',
  full_name='firestore_query.FirestoreQuery.WhereClause',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='where_field', full_name='firestore_query.FirestoreQuery.WhereClause.where_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comparator', full_name='firestore_query.FirestoreQuery.WhereClause.comparator', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='firestore_query.FirestoreQuery.WhereClause.string_value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reference_value', full_name='firestore_query.FirestoreQuery.WhereClause.reference_value', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_value', full_name='firestore_query.FirestoreQuery.WhereClause.timestamp_value', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='firestore_query.FirestoreQuery.WhereClause.int_value', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='firestore_query.FirestoreQuery.WhereClause.double_value', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FIRESTOREQUERY_WHERECLAUSE_COMPARATOR,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='where_value', full_name='firestore_query.FirestoreQuery.WhereClause.where_value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=293,
  serialized_end=658,
)

_FIRESTOREQUERY_ORDERCLAUSE = _descriptor.Descriptor(
  name='OrderClause',
  full_name='firestore_query.FirestoreQuery.OrderClause',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_field', full_name='firestore_query.FirestoreQuery.OrderClause.order_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='descending', full_name='firestore_query.FirestoreQuery.OrderClause.descending', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=660,
  serialized_end=714,
)

_FIRESTOREQUERY = _descriptor.Descriptor(
  name='FirestoreQuery',
  full_name='firestore_query.FirestoreQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='firestore_query.FirestoreQuery.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_collection_group', full_name='firestore_query.FirestoreQuery.is_collection_group', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='where_clauses', full_name='firestore_query.FirestoreQuery.where_clauses', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='firestore_query.FirestoreQuery.limit', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order_clauses', full_name='firestore_query.FirestoreQuery.order_clauses', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FIRESTOREQUERY_WHERECLAUSE, _FIRESTOREQUERY_ORDERCLAUSE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=714,
)

_FIRESTOREQUERY_WHERECLAUSE.fields_by_name['comparator'].enum_type = _FIRESTOREQUERY_WHERECLAUSE_COMPARATOR
_FIRESTOREQUERY_WHERECLAUSE.fields_by_name['reference_value'].message_type = common__pb2._DOCUMENTREFERENCEPROTO
_FIRESTOREQUERY_WHERECLAUSE.fields_by_name['timestamp_value'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_FIRESTOREQUERY_WHERECLAUSE.containing_type = _FIRESTOREQUERY
_FIRESTOREQUERY_WHERECLAUSE_COMPARATOR.containing_type = _FIRESTOREQUERY_WHERECLAUSE
_FIRESTOREQUERY_WHERECLAUSE.oneofs_by_name['where_value'].fields.append(
  _FIRESTOREQUERY_WHERECLAUSE.fields_by_name['string_value'])
_FIRESTOREQUERY_WHERECLAUSE.fields_by_name['string_value'].containing_oneof = _FIRESTOREQUERY_WHERECLAUSE.oneofs_by_name['where_value']
_FIRESTOREQUERY_WHERECLAUSE.oneofs_by_name['where_value'].fields.append(
  _FIRESTOREQUERY_WHERECLAUSE.fields_by_name['reference_value'])
_FIRESTOREQUERY_WHERECLAUSE.fields_by_name['reference_value'].containing_oneof = _FIRESTOREQUERY_WHERECLAUSE.oneofs_by_name['where_value']
_FIRESTOREQUERY_WHERECLAUSE.oneofs_by_name['where_value'].fields.append(
  _FIRESTOREQUERY_WHERECLAUSE.fields_by_name['timestamp_value'])
_FIRESTOREQUERY_WHERECLAUSE.fields_by_name['timestamp_value'].containing_oneof = _FIRESTOREQUERY_WHERECLAUSE.oneofs_by_name['where_value']
_FIRESTOREQUERY_WHERECLAUSE.oneofs_by_name['where_value'].fields.append(
  _FIRESTOREQUERY_WHERECLAUSE.fields_by_name['int_value'])
_FIRESTOREQUERY_WHERECLAUSE.fields_by_name['int_value'].containing_oneof = _FIRESTOREQUERY_WHERECLAUSE.oneofs_by_name['where_value']
_FIRESTOREQUERY_WHERECLAUSE.oneofs_by_name['where_value'].fields.append(
  _FIRESTOREQUERY_WHERECLAUSE.fields_by_name['double_value'])
_FIRESTOREQUERY_WHERECLAUSE.fields_by_name['double_value'].containing_oneof = _FIRESTOREQUERY_WHERECLAUSE.oneofs_by_name['where_value']
_FIRESTOREQUERY_ORDERCLAUSE.containing_type = _FIRESTOREQUERY
_FIRESTOREQUERY.fields_by_name['where_clauses'].message_type = _FIRESTOREQUERY_WHERECLAUSE
_FIRESTOREQUERY.fields_by_name['order_clauses'].message_type = _FIRESTOREQUERY_ORDERCLAUSE
DESCRIPTOR.message_types_by_name['FirestoreQuery'] = _FIRESTOREQUERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FirestoreQuery = _reflection.GeneratedProtocolMessageType('FirestoreQuery', (_message.Message,), {

  'WhereClause' : _reflection.GeneratedProtocolMessageType('WhereClause', (_message.Message,), {
    'DESCRIPTOR' : _FIRESTOREQUERY_WHERECLAUSE,
    '__module__' : 'query_pb2'
    # @@protoc_insertion_point(class_scope:firestore_query.FirestoreQuery.WhereClause)
    })
  ,

  'OrderClause' : _reflection.GeneratedProtocolMessageType('OrderClause', (_message.Message,), {
    'DESCRIPTOR' : _FIRESTOREQUERY_ORDERCLAUSE,
    '__module__' : 'query_pb2'
    # @@protoc_insertion_point(class_scope:firestore_query.FirestoreQuery.OrderClause)
    })
  ,
  'DESCRIPTOR' : _FIRESTOREQUERY,
  '__module__' : 'query_pb2'
  # @@protoc_insertion_point(class_scope:firestore_query.FirestoreQuery)
  })
_sym_db.RegisterMessage(FirestoreQuery)
_sym_db.RegisterMessage(FirestoreQuery.WhereClause)
_sym_db.RegisterMessage(FirestoreQuery.OrderClause)


# @@protoc_insertion_point(module_scope)
