name: web_mercator
description: web mercator bindings
version: 1.0.0
author: Jack

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  js: ^0.6.1
  meta: ^1.1.0
  node_interop: ^1.0.0

dev_dependencies:
  test: