import 'algolia_change_test.dart' as algolia_change;
import 'algolia_record_proto_test.dart' as algolia_record_proto;
import 'algolia_record_test.dart' as algolia_record;
import 'badges_test.dart' as badges;
import 'bookmark_test.dart' as bookmark;
import 'bug_report_test.dart' as bug_report;
import 'comments_count_test.dart' as comments_count;
import 'comments_like_updater_test.dart' as comments_like_updater;
import 'comments_notifications_test.dart' as comments_notifications;
import 'dedupe_restaurants_test.dart' as dedupe_restaurants;
import 'delete_restaurant_test.dart' as delete_restaurant;
import 'delete_user_badges_test.dart' as delete_user_badges;
import 'delete_user_test.dart' as delete_user;
import 'diff_test.dart' as diff;
import 'diff_update_test.dart' as diff_update;
import 'do_not_recreate_algolia_test.dart' as do_not_recreate_algolia;
import 'favorites_test.dart' as favorites;
import 'field_diff_test.dart' as field_diff;
import 'follow_test.dart' as follow;
import 'follower_test.dart' as follower;
import 'functions_test.dart' as functions;
import 'instagram_post_review_test.dart' as instagram_post_review;
import 'notifications_test.dart' as notifications;
import 'proto_transforms_test.dart' as proto_transforms;
import 'restaurant_test.dart' as restaurant;
import 'review_score_test.dart' as review_score;
import 'review_triggers_test.dart' as review_triggers;
import 'select_test.dart' as select;
import 'snapshot_test.dart' as snapshot;
import 'update_self_test.dart' as update_self;
import 'user_algolia_test.dart' as user_algolia;
import 'views_test.dart' as views;

void main() {
  algolia_change.main();
  algolia_record_proto.main();
  algolia_record.main();
  badges.main();
  bookmark.main();
  bug_report.main();
  comments_count.main();
  comments_like_updater.main();
  comments_notifications.main();
  dedupe_restaurants.main();
  delete_restaurant.main();
  delete_user_badges.main();
  delete_user.main();
  diff.main();
  diff_update.main();
  do_not_recreate_algolia.main();
  favorites.main();
  field_diff.main();
  follower.main();
  follow.main();
  functions.main();
  instagram_post_review.main();
  notifications.main();
  proto_transforms.main();
  restaurant.main();
  review_score.main();
  review_triggers.main();
  select.main();
  snapshot.main();
  update_self.main();
  user_algolia.main();
  views.main();
}
