name: taste
description: Consumer Taste Application
version: 1.3.2

environment:
  sdk: ">=2.7.0 <3.0.0"

# Try and keep overrides out of here so we can Cmd+Shift+P -> sort these items.
dependencies:
  flutter:
    sdk: flutter
  algolia:
  apple_sign_in: ^0.1.0
  appsflyer_sdk: ^1.2.5
  assorted_layout_widgets:
  async: ^2.3.0
  auto_size_text: ^2.1.0
  bloc:
  cached_network_image: ^2.3.0-beta
  cloud_firestore:
  cloud_functions:
  collection:
  country_code_picker: ^1.2.3
  dartx:
  dash_chat:
  deferrable: ^1.0.2
  dots_indicator: ^1.0.0
  edit_distance: ^0.4.1
  equatable:
  exif:
  expire_cache:
  fading_edge_scrollview:
  feature_discovery:
  firebase_analytics:
  firebase_auth: ^0.16.0
  firebase_crashlytics:
  firebase_dynamic_links:
  firebase_in_app_messaging:
  firebase_messaging:
  firebase_ml_vision:
  firebase_remote_config:
  firebase_storage:
  firebase_ui:
  flutter_bloc: ^4.0.0-dev.1
  flutter_cache_manager:
  flutter_contact: 0.4.14
  flutter_exif_rotation:
  flutter_facebook_login: ^3.0.0
  flutter_keyboard_visibility: ^2.0.0
  flutter_icons:
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9
  flutter_native_timezone:
  flutter_webview_plugin:
  flutter_sequence_animation:
  flutter_typeahead:
  flutter_slidable:
  flutter_staggered_grid_view:
  freezed_annotation:
  geocoder:
  geohash:
  get_version: ^0.2.0+1
  google_maps_flutter:
  google_maps_webservice:
  google_sign_in: ^4.0.14
  http: ^0.12.0+2
  image_cropper:
  image_crop:
  image_picker: ^0.6.1
  introduction_screen:
  localstorage:
  location: ^2.3.5
  logger: ^0.7.0+2
  meta:
  multi_image_picker:
  path_provider:
  pedantic:
  photo_view:
  protobuf:
  provider: ^4.0.1
  query_params: ^0.6.1
  quiver: ^2.0.5
  permission_handler: ^4.4.0
  preload_page_view:
  pull_to_refresh:
  recase:
  rxdart:
  s2geometry:
  scrollable_positioned_list:
  share:
  share_api:
  shared_preferences: ^0.5.6
  sliding_up_panel:
  smooth_page_indicator:
  stream_transform: ^1.1.0
  task_queue:
  taste_protos:
  timeago: ^2.0.21
  timezone:
  top_k:
  tuple: ^1.0.3
  vector_math:
  video_player:
  visibility_detector:
  web_mercator_dart:
  url_launcher:

dependency_overrides:
  firebase_core: 0.4.4
  keyboard_visibility:
    git:
      url: https://github.com/jackdreilly/flutter_keyboard_visibility
  multi_image_picker:
    git:
      url: https://github.com/jackdreilly/multi_image_picker
      ref: 3e8542f8cc16a7b4e1a97f7d3f3838af8a0f873d
  feature_discovery:
    path: ../third_party/feature_discovery-0.10.0
  firebase_ui:
    path: ../third_party/firebase_ui
  flutter_exif_rotation:
    path: ../third_party/flutter_exif_rotation-0.2.7
  geocoder:
    path: ../third_party/geocoder-0.2.1
  introduction_screen:
    path: ../third_party/introduction_screen-1.0.8
  material_segmented_control:
    git:
      url: git://github.com/beagle-barks/material_segmented_control.git
      ref: 3992111e6b5cb7ef58c0978627e7df0f14daa6f9
  share_api:
    git:
      url: https://github.com/rmena28/share_api
  s2geometry:
    path: ../third_party/dart-s2geometry
  task_queue:
    path: ../third_party/task-queue-dart
  taste_protos:
    path: ../taste_protos
  protoc_plugin:
    path: ../third_party/protobuf/protoc_plugin
  protobuf:
    path: ../third_party/protobuf/protobuf
  smooth_page_indicator:
    path: ../third_party/smooth_page_indicator
  preload_page_view:
    git: https://github.com/tasteapp/preload_page_view
  sliding_up_panel:
    path: ../third_party/sliding_up_panel-1.0.2
  web_mercator_dart:
    path: ../web_mercator_dart

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed:
  dependency_validator: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/ui/
    - assets/3p_icons/
    - assets/images/
    - assets/camera/
    - assets/characters/
    - assets/posting/
  fonts:
    - family: Acme
      fonts:
        - asset: assets/fonts/Acme/Acme-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
    - family: Hurley
      fonts:
        - asset: assets/fonts/Hurley/Hurley-1967-Script-Reg.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar/Lalezar-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
    - family: TrophyIcon
      fonts:
        - asset: assets/fonts/TrophyIcon/TrophyIcon.ttf
    - family: BookmarkIcon
      fonts:
        - asset: assets/fonts/BookmarkIcon/BookmarkIcon.ttf
    - family: GamificationIcon
      fonts:
        - asset: assets/fonts/GamificationIcon/GamificationIcon.ttf
    - family: FireIcon
      fonts:
        - asset: assets/fonts/FireIcon/FireIcon.ttf
    - family: TrophyOutlineIcon
      fonts:
        - asset: assets/fonts/TrophyOutlineIcon/TrophyOutlineIcon.ttf
    - family: PhotoLibraryIcon
      fonts:
        - asset: assets/fonts/PhotoLibraryIcon/PhotoLibraryIcon.ttf
    - family: EditFavoritesIcon
      fonts:
        - asset: assets/fonts/EditFavoritesIcon/EditFavoritesIcon.ttf
    - family: CameraIcon
      fonts:
        - asset: assets/fonts/CameraIcon/CameraIcon.ttf
    - family: PostingPhotoLibraryIcon
      fonts:
        - asset: assets/fonts/PostingPhotoLibraryIcon/PostingPhotoLibraryIcon.ttf
    - family: ExploreIcon
      fonts:
        - asset: assets/fonts/ExploreIcon/ExploreIcon.ttf
    - family: AddIcon
      fonts:
        - asset: assets/fonts/AddIcon/AddIcon.ttf
    - family: ProfileIcon
      fonts:
        - asset: assets/fonts/ProfileIcon/ProfileIcon.ttf
    - family: FilterIcon
      fonts:
        - asset: assets/fonts/FilterIcon/FilterIcon.ttf
    - family: DislikeButton
      fonts:
        - asset: assets/fonts/DislikeButton/DislikeButton.ttf
    - family: LikeButton
      fonts:
        - asset: assets/fonts/LikeButton/LikeButton.ttf
    - family: TasteIcons
      fonts:
        - asset: assets/fonts/TasteIcons/TasteIcons.ttf
    # Font weights: https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/ui/taste_app_icon_transparent.png"
  image_path_ios: "assets/ui/taste_app_icon_ios_no_alpha.png"

flutter_native_splash:
  color: "ffffff"
  image: "assets/ui/taste_logo.png"
