import 'package:taste_protos/extensions.dart';

const _countryTasteTags = [
  MapEntry('🇺🇸', 'United States'),
  MapEntry('🇨🇳', 'China'),
  MapEntry('🇦🇫', 'Afghanistan'),
  MapEntry('🇦🇲', 'Armenia'),
  MapEntry('🇦🇷', 'Argentina'),
  MapEntry('🇦🇹', 'Austria'),
  MapEntry('🇦🇺', 'Australia'),
  MapEntry('🇧🇪', 'Belgium'),
  MapEntry('🇧🇬', 'Bulgaria'),
  MapEntry('🇧🇴', 'Bolivia'),
  MapEntry('🇧🇷', 'Brazil'),
  MapEntry('🇨🇦', 'Canada'),
  MapEntry('🇨🇭', 'Switzerland'),
  MapEntry('🇨🇱', 'Chile'),
  MapEntry('🇨🇴', 'Colombia'),
  MapEntry('🇨🇺', 'Cuba'),
  MapEntry('🇨🇾', 'Cyprus'),
  MapEntry('🇩🇪', 'Germany'),
  MapEntry('🇪🇬', 'Egypt'),
  MapEntry('🇪🇸', 'Spain'),
  MapEntry('🇪🇹', 'Ethiopia'),
  MapEntry('🇫🇮', 'Finland'),
  MapEntry('🇫🇷', 'France'),
  MapEntry('🇬🇧', 'United Kingdom'),
  MapEntry('🇬🇷', 'Greece'),
  MapEntry('🇬🇪', 'Georgia'),
  MapEntry('🇭🇷', 'Croatia'),
  MapEntry('🇭🇹', 'Haiti'),
  MapEntry('🇮🇩', 'Indonesia'),
  MapEntry('🇮🇪', 'Ireland'),
  MapEntry('🇮🇱', 'Israel'),
  MapEntry('🇮🇳', 'India'),
  MapEntry('🇮🇶', 'Iraq'),
  MapEntry('🇮🇷', 'Iran'),
  MapEntry('🇮🇹', 'Italy'),
  MapEntry('🇯🇲', 'Jamaica'),
  MapEntry('🇯🇴', 'Jordan'),
  MapEntry('🇯🇵', 'Japan'),
  MapEntry('🇰🇭', 'Cambodia'),
  MapEntry('🇰🇷', 'South Korea'),
  MapEntry('🇱🇦', 'Laos'),
  MapEntry('🇱🇧', 'Lebanon'),
  MapEntry('🇱🇰', 'Sri Lanka'),
  MapEntry('🇲🇦', 'Morocco'),
  MapEntry('🇲🇲', 'Myanmar MapEntry(Burma)'),
  MapEntry('🇲🇳', 'Mongolia'),
  MapEntry('🇲🇽', 'Mexico'),
  MapEntry('🇲🇾', 'Malaysia'),
  MapEntry('🇳🇬', 'Nigeria'),
  MapEntry('🇳🇮', 'Nicaragua'),
  MapEntry('🇳🇱', 'Netherlands'),
  MapEntry('🇳🇴', 'Norway'),
  MapEntry('🇳🇵', 'Nepal'),
  MapEntry('🇵🇦', 'Panama'),
  MapEntry('🇵🇪', 'Peru'),
  MapEntry('🇵🇭', 'Philippines'),
  MapEntry('🇵🇰', 'Pakistan'),
  MapEntry('🇵🇱', 'Poland'),
  MapEntry('🇵🇷', 'Puerto Rico'),
  MapEntry('🇵🇸', 'Palestine'),
  MapEntry('🇵🇹', 'Portugal'),
  MapEntry('🇷🇴', 'Romania'),
  MapEntry('🇷🇸', 'Serbia'),
  MapEntry('🇷🇺', 'Russia'),
  MapEntry('🇸🇦', 'Saudi Arabia'),
  MapEntry('🇸🇩', 'Sudan'),
  MapEntry('🇸🇪', 'Sweden'),
  MapEntry('🇸🇬', 'Singapore'),
  MapEntry('🇸🇮', 'Slovenia'),
  MapEntry('🇸🇰', 'Slovakia'),
  MapEntry('🇸🇳', 'Senegal'),
  MapEntry('🇸🇴', 'Somalia'),
  MapEntry('🇸🇷', 'Suriname'),
  MapEntry('🇸🇸', 'South Sudan'),
  MapEntry('🇸🇻', 'El Salvador'),
  MapEntry('🇸🇾', 'Syria'),
  MapEntry('🇹🇭', 'Thailand'),
  MapEntry('🇹🇳', 'Tunisia'),
  MapEntry('🇹🇷', 'Turkey'),
  MapEntry('🇹🇼', 'Taiwan'),
  MapEntry('🇺🇦', 'Ukraine'),
  MapEntry('🇺🇾', 'Uruguay'),
  MapEntry('🇻🇪', 'Venezuela'),
  MapEntry('🇻🇳', 'Vietnam'),
  MapEntry('🇼🇸', 'Samoa'),
  MapEntry('🇾🇪', 'Yemen'),
  MapEntry('🇿🇦', 'South Africa'),
  MapEntry('🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'England'),
  MapEntry('🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Scotland'),
  MapEntry('🏴󠁧󠁢󠁷󠁬󠁳󠁿', 'Wales'),
];

const _emojiTags = [
  MapEntry('😋', 'face savoring food'),
  MapEntry('🤤', 'drooling face'),
  MapEntry('🤑', 'money expensive face'),
  MapEntry('🥵', 'hot face spicy sweaty'),
  MapEntry('😍', 'smile face heart love'),
  MapEntry('#vegan', 'vegan hashtag'),
  MapEntry('#veggie', 'vegan hashtag'),
  MapEntry('#paleo', 'paleo hashtag'),
  MapEntry('#meh', 'meh hashtag'),
  MapEntry('#cheatday', 'cheatday hashtag'),
  MapEntry('🤮', 'face vomiting puke barf'),
  MapEntry('🤷', 'person shrugging'),
  MapEntry('🔥', 'fire spicy'),
  MapEntry('🌿', 'leaf vegetable vegetarian vegan'),
  MapEntry('🍔', 'hamburger cheeseburger'),
  MapEntry('🧆', 'falafel'),
  MapEntry('🍗', 'poultry chicken leg'),
  MapEntry('🥩', 'cut of meat beef'),
  MapEntry('🥓', 'bacon'),
  MapEntry('🍟', 'french fries'),
  MapEntry('🍕', 'pizza'),
  MapEntry('🌭', 'hot dog'),
  MapEntry('🥪', 'sandwich'),
  MapEntry('🌮', 'taco'),
  MapEntry('🌯', 'burrito'),
  MapEntry('🥙', 'stuffed flatbread'),
  MapEntry('🍳', 'cooking egg'),
  MapEntry('🥘', 'shallow pan of food'),
  MapEntry('🍲', 'pot of food soup'),
  MapEntry('🥣', 'bowl with spoon'),
  MapEntry('🥗', 'green salad'),
  MapEntry('🍿', 'popcorn'),
  MapEntry('🧂', 'salt'),
  MapEntry('🥫', 'canned food'),
  MapEntry('🍱', 'bento box'),
  MapEntry('🍘', 'rice cracker'),
  MapEntry('🍙', 'rice ball'),
  MapEntry('🍚', 'cooked rice'),
  MapEntry('🍛', 'curry rice'),
  MapEntry('🍜', 'noodle steaming bowl'),
  MapEntry('🍝', 'spaghetti'),
  MapEntry('🍠', 'roasted sweet potato'),
  MapEntry('🥐', 'croissant'),
  MapEntry('🥖', 'baguette bread'),
  MapEntry('🥨', 'pretzel'),
  MapEntry('🥯', 'bagel'),
  MapEntry('🥞', 'pancakes'),
  MapEntry('🧀', 'cheese wedge'),
  MapEntry('🍖', 'meat on bone'),
  MapEntry('🍢', 'oden kabob kebab skewer'),
  MapEntry('🍣', 'sushi'),
  MapEntry('🍤', 'fried shrimp'),
  MapEntry('🍥', 'fish cake with swirl'),
  MapEntry('🥮', 'moon cake'),
  MapEntry('🍡', 'dango'),
  MapEntry('🥟', 'dumpling'),
  MapEntry('🥠', 'fortune cookie'),
  MapEntry('🥡', 'takeout box'),
  MapEntry('🍦', 'soft ice cream'),
  MapEntry('🍧', 'shaved ice'),
  MapEntry('🍨', 'ice cream'),
  MapEntry('🍩', 'doughnut'),
  MapEntry('🍪', 'cookie'),
  MapEntry('🎂', 'birthday cake'),
  MapEntry('🍰', 'shortcake'),
  MapEntry('🧁', 'cupcake'),
  MapEntry('🥧', 'pie'),
  MapEntry('🍫', 'chocolate bar'),
  MapEntry('🍬', 'candy'),
  MapEntry('🍭', 'lollipop'),
  MapEntry('🍮', 'custard'),
  MapEntry('🍯', 'honey pot'),
  MapEntry('🍼', 'baby bottle'),
  MapEntry('🥛', 'glass of milk'),
  MapEntry('☕', 'hot beverage coffee'),
  MapEntry('🍵', 'teacup without handle'),
  MapEntry('🍶', 'sake'),
  MapEntry('🍾', 'champagne bottle with popping cork'),
  MapEntry('🍷', 'wine glass'),
  MapEntry('🍸', 'cocktail glass'),
  MapEntry('🍹', 'tropical drink'),
  MapEntry('🍺', 'beer mug'),
  MapEntry('🍻', 'clinking beer mugs'),
  MapEntry('🥂', 'champagne clinking glasses'),
  MapEntry('🥃', 'tumbler glass'),
  MapEntry('🥤', 'cup with straw'),
  MapEntry('🥢', 'chopsticks'),
  MapEntry('🍽', 'fork and knife with plate'),
  MapEntry('🍴', 'fork and knife'),
  MapEntry('🥄', 'spoon'),
  MapEntry('🍇', 'grapes'),
  MapEntry('🍈', 'melon'),
  MapEntry('🍉', 'watermelon'),
  MapEntry('🍊', 'tangerine'),
  MapEntry('🍋', 'lemon'),
  MapEntry('🍌', 'banana'),
  MapEntry('🍍', 'pineapple'),
  MapEntry('🥭', 'mango'),
  MapEntry('🍎', 'red apple'),
  MapEntry('🍏', 'green apple'),
  MapEntry('🍐', 'pear'),
  MapEntry('🍑', 'peach'),
  MapEntry('🍒', 'cherries'),
  MapEntry('🍓', 'strawberry'),
  MapEntry('🥝', 'kiwi fruit'),
  MapEntry('🍅', 'tomato'),
  MapEntry('🥥', 'coconut'),
  MapEntry('🥑', 'avocado'),
  MapEntry('🍆', 'eggplant'),
  MapEntry('🥔', 'potato'),
  MapEntry('🥕', 'carrot'),
  MapEntry('🌽', 'ear of corn'),
  MapEntry('🌶', 'hot pepper'),
  MapEntry('🥒', 'cucumber'),
  MapEntry('🥬', 'leafy green'),
  MapEntry('🥦', 'broccoli'),
  MapEntry('🍄', 'mushroom'),
  MapEntry('🥜', 'peanuts'),
  MapEntry('🌰', 'chestnut'),
  MapEntry('🍞', 'bread'),
];

final kCountryTasteTagsMap = _countryTasteTags.mapify;
final kEmojiTagsMap = _emojiTags.mapify;
final kTasteTagsMap = (_emojiTags + _countryTasteTags).mapify;
