name: mailchimp
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/jackdreilly/mailchimp
author: Jack Reilly <jackdreilly@gmail.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
 http:
 node_interop:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
