package(default_visibility = ["//visibility:public"])
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_java//java:defs.bzl", "java_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "firebase_rules_options_proto",
    srcs = ["firebase_rules_options.proto"],
    deps = [
        "@com_google_protobuf//:descriptor_proto",
    ],
)
