#!/bin/bash
VIEWS=$(ls *_view.sql)
PROJ="FIREBASE_PROD_PROJECT"
for view in $VIEWS; do
  viewName=${view/_view.sql/}
  echo "Creating view: $viewName"
  viewQuery=$(cat $view)
  bq rm -f --project_id $PROJ views.$viewName
  bq mk \
    --use_legacy_sql=false \
    --description "auto-generated by //sql/create_views.sh." \
    --view "$viewQuery" \
    --project_id $PROJ \
    views.$viewName
done