-- Defines the `views.resto_place_types` view in Taste prod.
-- This query extracts "PlaceType" scores for different restaurants based on the
-- frequency of appearance of text in Yelp reviews. The column indices match
-- the number for the firestore.PlaceType enum. i.e. column index 1 (2nd column)
-- corresponds to enum-value 1: PlaceType#american_restaurant.
SELECT place,
    (COUNTIF(LOWER(text) LIKE '% american%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% coffee%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% fast food%') + COUNTIF(LOWER(text) LIKE '% fastfood%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% italian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% breakfast%') + COUNTIF(LOWER(text) LIKE '% brunch')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% bar%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% pizza%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% seafood%') + COUNTIF(LOWER(text) LIKE '% mussels%') + COUNTIF(LOWER(text) LIKE '% crab%') + COUNTIF(LOWER(text) LIKE '% octopus%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% bakery%') + COUNTIF(LOWER(text) LIKE '% croissant%') + COUNTIF(LOWER(text) LIKE '% pastry%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% new american%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% sushi%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% mexican%') + COUNTIF(LOWER(text) LIKE '% tacos %') + COUNTIF(LOWER(text) LIKE '% burritos %')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% bar and grill%') + COUNTIF(LOWER(text) LIKE '% bar & grill%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% ice cream%') + COUNTIF(LOWER(text) LIKE '% icecream%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% cafe%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% burger%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% family style%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% pub%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% asian fusion%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% sandwich%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% deli %') + COUNTIF(LOWER(text) LIKE '% delicatessen%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% caterer%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% diner%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% dessert%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% vegetarian%') + COUNTIF(LOWER(text) LIKE '% vegan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% barbecue%') + COUNTIF(LOWER(text) LIKE '% bbq%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% steakhouse%') + COUNTIF(LOWER(text) LIKE '% steak %')  + COUNTIF(LOWER(text) LIKE '% steaks %')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% chinese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% cocktail%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% thai%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% wine bar%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% french%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% korean%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% smoothie%') + COUNTIF(LOWER(text) LIKE '% juice bar%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% european%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% mediterranean%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% chicken joint%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% brewery%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% sports bar%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% japanese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% health food%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% tea room%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% donut%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% ramen%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% food and beverage%') + COUNTIF(LOWER(text) LIKE '% food & beverage%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% bubble tea%') + COUNTIF(LOWER(text) LIKE '% milk tea%') + COUNTIF(LOWER(text) LIKE '% boba%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% food truck%') + COUNTIF(LOWER(text) LIKE '% foodtruck%') + COUNTIF(LOWER(text) LIKE '% food-truck%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% tapas%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% gastropub%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% tex mex%') + COUNTIF(LOWER(text) LIKE '% tex-mex%') + COUNTIF(LOWER(text) LIKE '% texmex%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% southern%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% pho%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% spanish%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% food stand%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% grocery store%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% greek%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% farmers market%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% cantonese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% beer %')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% vietnamese%') + COUNTIF(LOWER(text) LIKE '% banh mi%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% middle eastern%') + COUNTIF(LOWER(text) LIKE '% middle-eastern%') + COUNTIF(LOWER(text) LIKE '% middleeastern%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% bagel%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% cupcake%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% indian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% dim sum%') + COUNTIF(LOWER(text) LIKE '% dimsum%') + COUNTIF(LOWER(text) LIKE '% dumpling%') + COUNTIF(LOWER(text) LIKE '% momos %')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% winery%') + COUNTIF(LOWER(text) LIKE '% vineyard%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% hawaiian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% poke %')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% beer garden%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% asian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% frozen yogurt%') + COUNTIF(LOWER(text) LIKE '% froyo%') + COUNTIF(LOWER(text) LIKE '% fro-yo%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% soup%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% latin american%') + COUNTIF(LOWER(text) LIKE '% latinamerican%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '%cajun%') + COUNTIF(LOWER(text) LIKE '%creole%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% hot dog%') + COUNTIF(LOWER(text) LIKE '% hotdog%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% halal%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% taiwanese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% candy store%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% creperie%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% salad bar%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% filipino%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% buffet%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% caribbean%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% gelato%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% cafeteria%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% peruvian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% southwestern%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% comfort food%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% cuban%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% gluten free%') + COUNTIF(LOWER(text) LIKE '% gluten-free%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% modern european%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% british%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% irish%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% noodle house%') + COUNTIF(LOWER(text) LIKE '% noodle soup%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% hot pot%') + COUNTIF(LOWER(text) LIKE '% hotpot%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '%fish and chips%') + COUNTIF(LOWER(text) LIKE '%fish n chips%') + COUNTIF(LOWER(text) LIKE '%fish & chips%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% kosher%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% soul food%') + COUNTIF(LOWER(text) LIKE '% soulfood%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% lebanese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% chocolate%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% portuguese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% shaved ice%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% brazilian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% szechuan%') + COUNTIF(LOWER(text) LIKE '% sichuan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% wine %') + COUNTIF(LOWER(text) LIKE '% spirits%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% turkish%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% german%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% argentinian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% dive bar%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% taco%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% australian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% irish pub%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '%raw food%') + COUNTIF(LOWER(text) LIKE '%live food%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% south indian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% persian%') + COUNTIF(LOWER(text) LIKE '% iranian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% fondue%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '%bed and breakfast%') + COUNTIF(LOWER(text) LIKE '%bed & breakfast%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% continental%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% whisky bar%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% teppanyaki%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% kebab%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% colombian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% pakistani%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% malaysian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% sake bar%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% indonesian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% belgian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% scandinavian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% theme%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% jamaican%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% shabu shabu%') + COUNTIF(LOWER(text) LIKE '% shabushabu%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% canadian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% hong kong%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% venezuelan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% israeli%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% north indian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% ethiopian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% singaporean%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% moroccan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% speakeasy%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% puerto rican%') + COUNTIF(LOWER(text) LIKE '% puertorican%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% neapolitan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% polynesian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% bavarian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% afghan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% shanghainese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% udon%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% tuscan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% yakitori%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% tiki %')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% yakiniku%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% roman%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% nepalese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% salvadoran%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% russian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% african%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% cambodian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% mongolian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% eastern european%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% abruzzo%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% bunsik%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% himalayan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% basque%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% tonkatsu%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% sicilian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% burmese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% south african%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% soba%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% polish%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% austrian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% dominican%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% bossam%') + COUNTIF(LOWER(text) LIKE '% jokbal%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% drive in%') + COUNTIF(LOWER(text) LIKE '% drive-in%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% swiss%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% hungarian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% arabian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% czech%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% okonomiyaki%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% indo chinese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% armenian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% hunan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% tempura%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% venetian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% unagi%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% georgian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% donburi%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% kaiseki%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% beijing%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% sri lankan%') + COUNTIF(LOWER(text) LIKE '% srilankan%') + COUNTIF(LOWER(text) LIKE '% sri-lankan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% scottish%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% indian chinese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% takoyaki%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% syrian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% balinese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% uzbek%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% emilia romagna%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% egyptian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% chilean%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% yoshoku%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% javanese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% catalan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% zhejiang%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% yunnan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% sukiyaki%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% gukbap%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% costa rican%') + COUNTIF(LOWER(text) LIKE '% costarican%') + COUNTIF(LOWER(text) LIKE '% costa-rican%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% bengali%') + COUNTIF(LOWER(text) LIKE '% bangladeshi%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% punjabi%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% molecular gastronomy%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% bolivian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% samgyetang%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% nabe%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% haitian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% guatemalan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% ecuadorian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% wagashi%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% ukrainian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% shaanxi%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% sardinian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% nicaraguan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% xinjiang%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% uruguayan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% shanxi%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% senegalese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% kushikatsu%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% janguh%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% gujarati%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% trinidadian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% romanian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% paraguayan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% panamanian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% padangnese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% nigerian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% monjayaki%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% marche%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% macanese%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% jiangsu%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% henan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% umbrian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% tamilian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% swabian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% parsi%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% molise%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% lombard%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% kurdish%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% kerala%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% huaiyang%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% honduran%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% hainan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% goan%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% dongbei%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% dhaba%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% calabrian%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% belizean%')) / COUNT(*),
    (COUNTIF(LOWER(text) LIKE '% acehnese%')) / COUNT(*)
FROM `firestore_export.yelp_reviews`
GROUP BY 1;